# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 * * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 14
        days-before-pr-stae: 14
        remove-stale-when-updated: true
        delete-branch: false
        exempt-all-milestones: true
        exempt-all-pr-milestones: true
        exempt-draft-pr: true
        exempt-issue-labels: open discussion,Batch 6
        stale-issue-message: 'This issue has been inactive for more than 14 days. Remove stale label or comment or this will be closed in 90 days.'
        stale-pr-message: 'Pull request is stale'
        stale-issue-label: 'STALE'
        stale-pr-label: 'STALE'
        days-before-close: 90
        days-before-pr-close: -1
